# Generated by Django 4.2.1 on 2023-06-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile_remove_log_user_log_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-date']},
        ),
    ]
