# Generated by Django 4.2.1 on 2023-06-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='coordinates',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
