# Generated by Django 4.2.2 on 2023-06-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='coordinates',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
